import os.path

CCFLAGS = "-I/home/yifei/.local/include -std=c++17 -O3"

OUTPUT_DIR = "bin"

ch7 = os.path.join(OUTPUT_DIR, "ch7")
ch12 = os.path.join(OUTPUT_DIR, "ch12")
ch13 = os.path.join(OUTPUT_DIR, "ch13")
ch14 = os.path.join(OUTPUT_DIR, "ch14")
ch15 = os.path.join(OUTPUT_DIR, "ch15")
ch16 = os.path.join(OUTPUT_DIR, "ch16")

Program(
    ch7,
    ["ch7_class.cpp", "sales_data.cpp", "screen.cpp", "account.cpp", "utils.cpp"],
    CCFLAGS=CCFLAGS,
)


Program(
    ch12,
    [
        "ch12_dynamic_memory.cpp",
        "utils.cpp",
        "str_blob.cpp",
        "str_blob_ptr.cpp",
        "text_query.cpp",
        "query_result.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch13,
    [
        "ch13_copy_control.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch14,
    [
        "ch14_operator_overloading.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch15,
    [
        "ch15_oop.cpp",
        "utils.cpp",
        "basket.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch16,
    [
        "ch16_template.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)
