import os.path

CCFLAGS = "-I/home/yifei/.local/include -std=c++17 -O3"

OUTPUT_DIR = "bin"

ch7 = os.path.join(OUTPUT_DIR, "ch7")
ch9 = os.path.join(OUTPUT_DIR, "ch9")
ch10 = os.path.join(OUTPUT_DIR, "ch10")
ch11 = os.path.join(OUTPUT_DIR, "ch11")
ch12 = os.path.join(OUTPUT_DIR, "ch12")
ch13 = os.path.join(OUTPUT_DIR, "ch13")
ch14 = os.path.join(OUTPUT_DIR, "ch14")
ch15 = os.path.join(OUTPUT_DIR, "ch15")
ch16 = os.path.join(OUTPUT_DIR, "ch16")
ch17 = os.path.join(OUTPUT_DIR, "ch17")
ch18 = os.path.join(OUTPUT_DIR, "ch18")
ch19 = os.path.join(OUTPUT_DIR, "ch19")

Program(
    ch7,
    ["ch7_class.cpp", "sales_data.cpp", "screen.cpp", "account.cpp", "utils.cpp"],
    CCFLAGS=CCFLAGS,
)

Program(
    ch9,
    ["ch9_sequential_container.cpp", "utils.cpp"],
    CCFLAGS=CCFLAGS,
)

Program(
    ch12,
    [
        "ch12_dynamic_memory.cpp",
        "utils.cpp",
        "str_blob.cpp",
        "str_blob_ptr.cpp",
        "text_query.cpp",
        "query_result.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch13,
    [
        "ch13_copy_control.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch14,
    [
        "ch14_operator_overloading.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch15,
    [
        "ch15_oop.cpp",
        "utils.cpp",
        "basket.cpp",
        "quote.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch16,
    [
        "ch16_template.cpp",
        "ch16_template_instance.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch17,
    [
        "ch17_stdlib.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch18,
    [
        "ch18_tools.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)

Program(
    ch19,
    [
        "ch19_special_tools.cpp",
        "utils.cpp",
    ],
    CCFLAGS=CCFLAGS,
)
